### ISSUE TITLE
多行拖尾逗号应该被提倡

### ISSUE THREAD

**Issue by int64ago** [kaola-fed/eslint-config-kaola#2]
最明显的好处就是 git diff 会很干净，减少合并代码的冲突，具体见[规则描述](http://eslint.org/docs/rules/comma-dangle)

目前的规则却直接禁止：https://github.com/kaola-fed/eslint-config-kaola/blob/master/index.js#L46

这个感觉不是很合理，考虑到兼容性，可以考虑改为：
`"comma-dangle": ["error", "only-multiline"]`

@force2008 @Deol   @fengzilong @ImHype

**Comment by Deol** [comment]
定义这个规则的主要原因是：

> 在 IE8（非 IE8 文档模式）下，当出现拖尾逗号，则会抛出错误。

**Comment by int64ago** [comment]
这个貌似只有 PC web 有这个需求？

**Comment by nanokind** [comment]
举双手赞成🙌

**Comment by int64ago** [comment]
工程 .eslintrc 自行添加忽略， Close
